type: dataset
id: 10
name: 0010_dataset
dir_name: datasets
lab_name: extraction_lab
rel_path: extraction_lab/datasets/0010_dataset
remarks: 100 synthetic samples
emb_model_config: null
parent_config: null
timestamp_init: 2025-01-08_13-09-57
