type: llm_pipeline
id: 4
name: 0004_llm_pipeline
dir_name: llm_pipelines
lab_name: extraction_lab
rel_path: extraction_lab/llm_pipelines/0004_llm_pipeline
name_or_path: microsoft/Phi-3-medium-128k-instruct
pipeline_args:
  return_full_text: false
  clean_up_tokenization_spaces: true
bnb_config:
  load_in_4bit: true
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: nf4
inference_tokenizer_config:
  padding_side: left
  padding: longest
  add_special_tokens: true
  max_length: 8192
  pad_token: <s>
training_tokenizer_config:
  padding_side: right
  padding: longest
  add_special_tokens: true
  max_length: 8192
  pad_token: <|endoftext|>
generation_config:
  return_dict_in_generate: false
  max_new_tokens: 750
  max_time: 600
  stop_strings: null
  pad_token: <s>
base_model: Phi-3-medium-128k-instruct
timestamp_init: 2025-01-03_13-43-30
