type: dataset
id: 8
name: 0008_dataset
dir_name: datasets
lab_name: extraction_lab
rel_path: extraction_lab/datasets/0008_dataset
remarks: small test dataset
emb_model_config: null
parent_config: null
timestamp_init: 2025-01-03_13-35-44
