type: dataset
id: 5
name: 0005_dataset
dir_name: datasets
lab_name: extraction_lab
rel_path: extraction_lab/datasets/0005_dataset
remarks: 100 real samples, cleaned double whitespaces, train/test split 70/30
emb_model_config: null
parent_config: null
timestamp_init: 2025-01-03_10-19-41
