type: dataset
id: 4
name: 0004_dataset
dir_name: datasets
lab_name: extraction_lab
rel_path: extraction_lab/datasets/0004_dataset
remarks: 100 real samples
emb_model_config: null
parent_config: null
timestamp_init: 2025-01-02_14-00-26
