type: dataset
id: 11
name: 0011_dataset
dir_name: datasets
lab_name: extraction_lab
rel_path: extraction_lab/datasets/0011_dataset
remarks: 100 real samples + 70 synthetic samples (train only)
emb_model_config: null
parent_config: null
timestamp_init: 2025-01-08_13-23-40
