type: llm_pipeline
id: 1
name: 0001_llm_pipeline
dir_name: llm_pipelines
lab_name: extraction_lab
rel_path: extraction_lab/llm_pipelines/0001_llm_pipeline
name_or_path: mistralai/Mistral-7B-Instruct-v0.2
pipeline_args:
  return_full_text: false
  clean_up_tokenization_spaces: true
bnb_config:
  load_in_4bit: true
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: nf4
inference_tokenizer_config:
  padding_side: left
  padding: longest
  add_special_tokens: true
  max_length: 8192
  pad_token: <unk>
training_tokenizer_config:
  padding_side: right
  padding: longest
  add_special_tokens: true
  max_length: 8192
  pad_token: <unk>
generation_config:
  return_dict_in_generate: false
  max_new_tokens: 750
  max_time: 600
  pad_token: <unk>
base_model: Mistral-7B-Instruct-v0.2
timestamp_init: 2024-12-06_17-25-00
