type: dataset
id: 7
name: 0007_dataset
dir_name: datasets
lab_name: extraction_lab
rel_path: extraction_lab/datasets/0007_dataset
remarks: 100 synthetic + 100 real samples, cleaned double whitespaces, train/test
  split 70/30
emb_model_config: null
parent_config: null
timestamp_init: 2025-01-03_12-34-24
