type: dataset
id: 9
name: 0009_dataset
dir_name: datasets
lab_name: extraction_lab
rel_path: extraction_lab/datasets/0009_dataset
remarks: 100 real samples
emb_model_config: null
parent_config: null
timestamp_init: 2025-01-08_12-49-53
