type: dataset
id: 2
name: 0002_dataset
path: /home/fboehning/fboehning/extraction_lab/datasets/0002_dataset
parent_dir_path: /home/fboehning/fboehning/extraction_lab/datasets
parent_lab_path: /home/fboehning/fboehning/extraction_lab
datetime_init: 2024-11-25 15:12:23.275636+01:00
remarks: 100 synthetic samples
dir_name: datasets
lab_name: extraction_lab
rel_path: extraction_lab/datasets/0002_dataset
