type: extraction_pipeline
id: 8
name: 0008_extraction_pipeline
dir_name: extraction_pipelines
lab_name: extraction_lab
rel_path: extraction_lab/extraction_pipelines/0008_extraction_pipeline
use_extraction_prompt: true
use_few_shots: true
llm_config:
  type: llm_pipeline
  id: 3
  name: 0003_llm_pipeline
  dir_name: llm_pipelines
  lab_name: extraction_lab
  rel_path: extraction_lab/llm_pipelines/0003_llm_pipeline
  pipeline_args:
    return_full_text: false
    clean_up_tokenization_spaces: true
  bnb_config:
    load_in_4bit: true
    bnb_4bit_use_double_quant: true
    bnb_4bit_quant_type: nf4
  inference_tokenizer_config:
    padding_side: left
    padding: longest
    add_special_tokens: true
  training_tokenizer_config:
    padding_side: right
    padding: longest
    add_special_tokens: true
  generation_config:
    return_dict_in_generate: false
    max_new_tokens: 750
    max_time: 600
    stop_strings:
    - '}

      ```'
  timestamp_init: 2024-12-06_17-26-33
timestamp_init: 2024-12-06_17-26-33
