framework_dirs:
- /home/fboehning/fboehning
module_path: /home/fboehning/fboehning/beesup_llm/experiment/extraction_experiment.py
script_path: /home/fboehning/fboehning/beesup_llm/experiment/multirun_script.py
experiment_dirs:
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0037_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0038_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0039_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0040_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0041_extraction_experiment
