framework_dirs:
- /home/fboehning/fboehning
module_path: /home/fboehning/fboehning/beesup_llm/experiment/extraction_experiment.py
script_path: /home/fboehning/fboehning/beesup_llm/experiment/multirun_script.py
experiment_dirs:
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0047_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0048_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0049_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0050_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0051_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0052_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0053_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0054_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0055_extraction_experiment
