framework_dirs:
- /home/fboehning/fboehning
module_path: /home/fboehning/fboehning/beesup_llm/experiment/extraction_experiment.py
script_path: /home/fboehning/fboehning/beesup_llm/experiment/multirun_script.py
experiment_dirs:
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0058_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0059_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0060_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0061_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0062_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0063_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0064_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0065_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0066_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0067_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0068_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0069_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0070_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0071_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0072_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0073_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0074_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0075_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0076_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0077_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0078_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0079_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0080_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0081_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0082_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0083_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0084_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0085_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0086_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0087_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0088_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0089_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0090_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0091_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0092_extraction_experiment
- /home/fboehning/fboehning/extraction_lab/extraction_experiments/0093_extraction_experiment
