type: gen_model
id: 1
name: 0001_gen_model
path: /home/fboehning/fboehning/extraction_lab/gen_models/0001_gen_model
parent_dir_path: /home/fboehning/fboehning/extraction_lab/gen_models
parent_lab_path: /home/fboehning/fboehning/extraction_lab
name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
base_model: Meta-Llama-3.1-8B-Instruct
datetime_init: 2024-11-25 15:24:33.463946+01:00
bnb_config:
  load_in_4bit: true
  bnb_4bit_use_double_quant: true
  bnb_4bit_quant_type: nf4
inference_tokenizer_config:
  padding_side: left
  padding: longest
  add_special_tokens: true
  max_length: 8192
  pad_token: <|begin_of_text|>
  pad_token_id: 128000
training_tokenizer_config:
  padding_side: right
  padding: longest
  add_special_tokens: true
  max_length: 8192
  pad_token: <|end_of_text|>
  pad_token_id: 128001
generation_config:
  return_dict_in_generate: false
  max_new_tokens: 750
  max_time: 600
  stop_strings: null
  pad_token: <|begin_of_text|>
  pad_token_id: 128000
data_collator_config:
  label_pad_token_id: -100
dataloader_config:
  batch_size: 4
dir_name: gen_models
lab_name: extraction_lab
rel_path: extraction_lab/gen_models/0001_gen_model
